name: test_impact
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  go_router: ^4.1.1
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  equatable: ^2.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  